# Generated by Django 5.1.4 on 2024-12-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_userprofile_email_alter_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=255)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('frequency', models.CharField(max_length=100)),
            ],
        ),
    ]
